version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=seu_usuario
      - POSTGRES_PASSWORD=sua_senha
      - POSTGRES_DB=meu_banco_de_dados
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seu_usuario -d meu_banco_de_dados"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spring_app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/meu_banco_de_dados
      - DB_USERNAME=seu_usuario
      - DB_PASSWORD=sua_senha
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: